# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TS and TJ
tab_title: TS and TJ - Two Idiots, One Common Name #This text shows up on the browser tab
email:
description: Two Idiots, One Common Name
url: "https://theamber.github.io/TS-and-TJ/" # the base hostname & protocol for your site

# Comic Social Media
twitter_username: http://twitter.com/tsandtj
#tumblr_username: http://peahat.tumblr.com
#patreon_username: peahat

# Author Social Media
author_twitter_username:ambernspence
#author_tumblr_username:
#author_patreon_username:



# Build settings
markdown: kramdown
theme: minima
